### ISSUE TITLE
Think about who might be interested in the demo

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#131]

**Comment by ydemchen** [comment]
I would like to ask if we want to consider other dates and paces for first CYCLONE demo
EGI2015 Community Forum 10-13 Nov 2015 Bari, Italy (require registration fee but access to 400-500 attendees from research community) - deadline 12 July 2015
UCC2015 conference 7-10 Dec 2015, Cyprus where we will organise NetCloud2015 workshop  and have 1-2 papers to present

**Comment by Josyab** [comment]
Hi Yuri, 

reading the content of the issue you created the title sounds more like " in which other places we could be presenting the demo", isn´t it?

For the "Think about who might be interested in the demo" we could consider the Géant Cloud service activity (it was SA7 in previous GN3p, but it´s unknown to me which one is in the current GN4, who is leading it (maybe Andres Steijaert?) it and if the scope of what they are proposing there matches somehow our Cloud federated environment. I cannot access the GN4 Intranet because there are no credertial for third parties.....so i cannot check this. But it could be a good candidate to see if they could be interesting on attending to the demo. ...Any other JRA or SA Géant activities?

It could also be interesting to see if the H2020 BEACON project "Enabling Federated Cloud Networking" (http://www.beacon-project.eu/). I have the contact of the TM.

**Comment by mathiasslawik** [comment]
There was no demo.
