### ISSUE TITLE
Create SlipStream deployment recipe for Federation Provider

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#132]

**Comment by ilke-zilci** [comment]
Docker based first version available at the Stratuslab instance of SlipStream:
https://slipstream.stratuslab.eu/module/CycloneFP/keycloak/899

**Comment by lodygens** [comment]
Well done, but seems impossible to start a new instance to test it, from slipstream.

On the other hand, a VM is running at LAL (134.158.75.222), but:
- it is not possible to ssh root@134.158.75.222 because you did certainly not provide our (end users) public keys
- keycloak seems not running on  http://134.158.75.222:9080

cheers

**Comment by mathiasslawik** [comment]
Hello Oleg,

the URL is http://134.158.75.222/auth

cheers

**Comment by lodygens** [comment]
thanks
