### ISSUE TITLE
Make sure CYCLONE base images remain on StratusLab marketplace

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#136]
Needed for the deployment of the CYCLONE components (Logging and Federation Provider) via SlipStream on StratusLab.

**Comment by lodygens** [comment]
Hi,
the marketplace itself does not store images themselves, but metadata only, each containing an image informations. Among them is the URI which helps to retrieve the image itself.
Hence, metadata longevity must be and is ensured by Stratuslab marketplace. But it is the image holder responsibility to ensure the image integrity.

Hope this helps,
Oleg Lodygensky

**Comment by ilke-zilci** [comment]
So the best way would be to have the image somewhere at TU Berlin servers and not use one of the listed images by other users, right?

**Comment by lodygens** [comment]
Or to trust a partern 
;)

The image you use is based on CentOS 6 stored at LAL. So its perenity is ensured.

The only thing is that you have chosen a "expired" image (https://marketplace.stratuslab.eu/marketplace/metadata/Ovo1LvwVgNUKhKCBSxUC_Endq9B/images@stratuslab.eu/2015-01-26T15:45:48Z) which is a pity since clouds may refuse to launch instances based on expired and or deprecated images (depending on the cloud policy as set by the cloud administrator)

cheers

**Comment by lodygens** [comment]
(this image has expired since last July, 23rd)

**Comment by ilke-zilci** [comment]
Can you extend the validity period of that image?

**Comment by lodygens** [comment]
only the endorser can do that

**Comment by lodygens** [comment]
In fact, you have created a Slipstream project (https://slipstream.stratuslab.eu/module/CycloneFP/keycloak) based on a CentOS6 image already registered on Sliptream (https://slipstream.stratuslab.eu/module/examples/images/centos-6), which is based on 4 images (CCIN2P3, IPHC, LAL, LUPM).

Unfortunately image at LAL has an expired validity and is subject to be not launchable. I don't know what about the others.

We understand here that we have a three levels rocket: 
1. your Slipstream project where you have defined read only authorizations
2. the "CentOS6" Slipstream project (your project is based on) where authorizations are extended to the group. But I don't know who is this project owner since it is labelled "super", and I can't see what user group it may concern.
3. images deployed over several cloup providers

At this point,I only see the following solution:
1. a Cyclone group should be created in Slipstream
2. a Cyclone group member could create an appliance with extended authorizations
3. you could then extend authorization to the group, if you ant to delegate

Hope this helps.

**Comment by lodygens** [comment]
By the way, we can't click "run" anymore in Slipstream web page, for this appliance...
Any idea?

**Comment by loomis** [comment]
There are several issues here. 

The first is the way StratusLab endorsements work.  Anyone can endorse an image and upload the signed metadata to the Marketplace; an image can have multiple endorsers.  The endorser can choose how long their endorsement of the image lasts.  By default, any image with a valid endorsement can be started on a StratusLab cloud.  Concretely, anyone can endorse the image which has expired to make it available again.  See the StratusLab docs on how to do that.

However, it is bad practice to endorse an image for a long period of time.  The images are fixed and do not evolve; consequently, they **do not** have security patches applied to them.  It is up to the cloud provider to supply images for basic operating systems that are updated regularly.  For SlipStream, our standard examples use Ubuntu 12.04 and more recently now Ubuntu 14.04.  We also expect that there is a current image for CentOS 6.  Images for CentOS 7 and CoreOS are nice to have as well. Grigory at LAL was the one making the new images when I left.

To track those images on particular cloud providers, we regularly update the image identifiers on the instances of SlipStream that we (SixSq) manage (our Nuvla service and the SlipStream server for Helix Nebula).  We do not maintain the SlipStream service at LAL, but do provide best-effort support for operational problems. Concretely, the maintainer of the SlipStream service at LAL (probably Guillaume) needs to update the image identifiers when the standard images are updated.  If someone at LAL, doesn't have the passwords, I can give them to you, assuming that they haven't been changed.

The maintainer can also extend the permissions to a CYCLONE group, if you want.  Either the owner of the image (probably the "sixsq" account) or the "super" account can do this.

There is still an open question about the SlipStream service for CYCLONE.  I'm still discussing with my colleagues here, but it is quite likely that we'll add the connectors for StratusLab and for QSC (once I know what cloud is used) to our SaaS instance of SlipStream (https://nuv.la).  If for some reason, we cannot do this, then we'll deploy and maintain a separate instance for the project.  In both cases, the cloud providers (LAL and QSC) will still be responsible for providing the base images for the project (and their users).

**Comment by lodygens** [comment]
Stratuslab images have been updated:
https://github.com/StratusLab/image-recipes/issues/27#issuecomment-137757927

**Comment by ilke-zilci** [comment]
Follow on appliance creation workflow. https://github.com/cyclone-project/cyclone-tracking/issues/140
