### ISSUE TITLE
Provide feedback on the version 1.0 of D3.1

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#152]
I uploaded a first version of the D3.1 “Evaluation of use cases“ to OneDrive and awaiting for comments.

The document (CYCLONE_D3.1-v1.0) is available in Cyclone > WP3 > Deliverables and milestones > D3.1

It would be helpful to have feedback from you on the general document, but in particular for the following chapters, I am expecting a contribution from the listed partners :
- Energy use case : QSC
- Common list of requirements : ALL
- Description of the software infrastructure : LAL, I2CAT, TUB, SixSq
- Description of the software infrastructure : LAL, QSC, IRT
- Infrastructure implications of the use cases requirements: ALL
- Evaluation of use cases : ALL
- Potential new use cases : ALL
- Preliminary market analysis and business model investigations : IRT, SixSq, QSC, i2CAT

**Comment by Josyab** [comment]
Hi all, 

I made a detailed review of sections 1, 2.1 and 2.2 ( i will continue tomorrow with the rest of the document), Some general comments:

1.- The verbal tense has to be homogenized across the document.

2.- Dedicate a section to the references and another one to the acronyms and move all of them.

3.- select U.K spelling or U.S spelling but don´t mix them.

4.- I made already 83 comments and changes. Section 1, 2.1 and 2.2 can start polishing the documents. In case you may have any doubts on my comments, please contact me. In general the document needs a lot of work and re-edition:
Homogeneize the structure of the use cases.
Provide figures and explain them
Include references to CYCLONE objectives, ambition, exploitation.
Include the "roles and actors section" (i don´t know why did this disapeared as it was in the milestone.
5.- In general is not easy to follow the se case, since it´s a use case coming from the “complex” genomic processing environment. Some of my comments are driven to clarify aspects that maybe well known in the context of the “bioinformatics environment” but not necessarily in the Cloud federation environment. Thus make sure that the description of the use cases defines all the terms that are involved. My suggestion would be to include before the “workflow” section, another section (name it “Use case concepts” or something similar) and define there all the components that may not be straightforward to understand. Most of my comments that require from a definition fall in this category.


Also i would like to thank Christophe for triggering the review process. I have some minor comments to the assignments (changes in green):

-  Bionformaics use case: I2CAT
- Energy use case : I2CAT (makes no sense that QSC reviews theit own contribution ;)).
- Common list of requirements : TUB, SIXSQ, I2CAT, IRT
- Description of the software infrastructure : LAL, I2CAT, TUB, SixSq
- Description of the software infrastructure : LAL, QSC, IRT
- Infrastructure implications of the use cases requirements: ALL
- Evaluation of use cases : ALL
- Potential new use cases : ALL
- Preliminary market analysis and business model investigations : IRT, SixSq, QSC ( I deleted I2CAT since we cannot provide input in terms of market analysis or business models")


The document is in OneDrive and also attached.

https://onedrive.live.com/redir?resid=2C3033FE409659BD!605&authkey=!ANZA7PtQQF53wEk&ithint=file%2cdocx

**Comment by mathiasslawik** [comment]
I've made some additions and comments to the document and created the file "CYCLONE_D3.1-v1.0_TUB_additions.docx".

In general I can confirm the comments of José. The most issues I have is with the QSC part because - unlike in the energy use case - after almost 10 months I still don't know exactly what TUB is supposed to do. This is caused by the missing information on the components which are already developed and deployed and the additional functionality we are supposed to provide - and how.

I don't even know what platform we are going to integrate! There is only one information "unix-like systems" - this could mean Minix, Linux, Darwin, FreeBSD, NetBSD, OpenBSD, AIX, Solaris and HP-UX. So - the QSC energy use case and its implications are completely unclear to me.

**Comment by cblanchet** [comment]
Comments and contributions from partners I2CAT, IRT, SixSQ, TUB were integrated and a new version was released (2.0)
