### ISSUE TITLE
Discuss approach to data erasure

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#159]
There is requirement 15 regarding secure data erasure. IFB and LAL should discuss how should this data erasure be performed and if there are tasks need to be implemented within the CYCLONE components.

**Comment by lodygens** [comment]
* using Stratuslab middleware **at LAL**
    * the boot disk is in quarantine 15mn after VM shutdown, then completely and definitely erased.
    * any end user disk are under the end user responsibility.
        * The end user must delete the disk manually 
* using OpenStack
    * there is no quarantine mechanism
    * LAL will investigate this topic more deeply.

**Comment by cblanchet** [comment]
We can manage it at the bioinformatics application level. But need also that there are no snapshot or quarantine.

**Comment by lodygens** [comment]
As deployed today, Boot image are in quarantine 15mn. This will not be changed.
It would then be the end user reponsibility to write no sensitiva data on boot image.

**Comment by lodygens** [comment]
Data erasure could hardly (if not) by certified by CSP. The only way I see is using LiveCD or LiveDVD where written data are stored in RAM only. All data are lost and not recoverable at VM shutdown or power off.
I am writing scripts to automate LiveCD creation.
In order to be able to create appliance, I would need the end user software stack.

**Comment by lodygens** [comment]
I would also need expected OS.

**Comment by mathiasslawik** [comment]
Couldn't we just change the shutdown scripts of a VM so that it uses dd to overwrite the block level devices with zeros or garbage? Like, put dd if=/dev/zero of=/dev/vda bs=4M at the end of the script?

**Comment by lodygens** [comment]
I'm affraid this does not totally ensure data erasure. What if the VM does not have a chance to run that script because it shuts down in an impromptu manner (electric power failure)?
IFB use case strongly requires data erasure and, to my mind, the only way to ensure such a strong requirement is to make sure nothing is written on any medium.

**Comment by lodygens** [comment]
I would like to ask IFB if they are interested by this solution. Is so, I would need the software stack to create and test a new LiveCD/LiveDVD.

**Comment by lodygens** [comment]
Scripts to automate LiveCD creation are in
 https://github.com/cyclone-project/data-erasure
