### ISSUE TITLE
Discuss how to handle the ports when PAM module is deployed at IFB Cloud

### ISSUE THREAD

**Issue by ilke-zilci** [cyclone-project/cyclone-tracking#189]
On the IFB cloud from outside only http, https, ssh ports are accessible. We can add a parameter in the deployment recipe to allow a 3rd port and proxy to it with another vm or IFB cloud allows another port.

**Comment by Sturgelose** [comment]
This has been implemented in commit https://github.com/cyclone-project/cyclone-python-pam/commit/e1f682dcfd64ecacbefde2e38df385b2ca84604d

It works loading a configuration file to the PAM module where you can set specific ports or ranges of ports available for the module to be used. Then the PAM module will take a random port from this set of available ports in order to spawn the server. In case the port is already in use, the module will try to retry in a different port.
