### ISSUE TITLE
Evaluate how to demonstrate the network part of the solution during the review 

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#203]
See how do we want to demonstrate the networking part of the solution in the review.

**Comment by isartcanyameres** [comment]
- Idea: Take two wordpress instances (with different templates to visually identify them), with a loadbalancer, firewall and VPN. Deploy them one in each cloud. With a wirewall denying traffic to common ports but allowing http. Demonstrate VPN by pinging the VMs public IP address (will fail because of firewall) but pinging through VPN -enabled interfaces will work.

**Comment by Josyab** [comment]
The idea is fine to demonstrate the Services.
The approach will be the following: If we can incorporate all the network services to the Demo, right. Otherwise, those aspects which may not be easy to visualize (e.g. automation of processes) we can place in the website and/or CYCLONE youtube channel the demos of the network services and features that have not been shown in the demo (for instance, as Isart proposes).
