### ISSUE TITLE
Solve Zettabox issues

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#29]
Zettabox folder was created. Still soem issues remains:

The tools crashes from time to time.
Solve "-" issue while inviting users to join the folder with the proposer email addresses.

**Comment by Josyab** [comment]
Already in contact with Zettabox support to fix this.

**Comment by lodygens** [comment]
I have two Apple computers running Mac OS 10.9.5:
- Mac Pro 4,1 with 12Gb ram: Zettabox runs well
- Mac BookPro 8,1 with 8Gb where, at Zettabox launch time, a dialog box opens complaining that the "nwmode" is not supported as shown in attached file (in french)

![zettaboxerror](https://cloud.githubusercontent.com/assets/6367731/6523957/03ae9578-c3f5-11e4-8e60-f064d9545c2d.png)

**Comment by lodygens** [comment]
For the 1st time ever, my Mac Pro 4,1 had a out of memory error. I suspect Zettabox since it is the last installed application. Please check Zettabox does not use all available memory.

In the attached file, it is written "Your system has used all allocated memory"; all applications have been forced in "pause" and thie only thing I could do is reboot my computer.
![zettabox_mem_err](https://cloud.githubusercontent.com/assets/6367731/6551679/b8c555fc-c63c-11e4-8383-11a1777f4313.jpg)

**Comment by lodygens** [comment]
You may especially glance what happens when network is down
:)

**Comment by qshacker** [comment]
I've the same issues with Mac OS 10.10; there is no connection to "nwnode:"

**Comment by Josyab** [comment]
Zettabox issues were not solved. We will be changing to other tool (probably DriveOne). it will be confirmed during the Demo meeting.
