### ISSUE TITLE
Lead discussion on TRESOR Tutorial content

### ISSUE THREAD

**Issue by mathiasslawik** [cyclone-project/cyclone-tracking#44]
I'd like to collect your opinions on what we should present you about the TRESOR components.

Possible topics include, but are not limited to:

* TRESOR Ecosystem
 * Overview
 * [Fig-based demo deployment](https://github.com/TU-Berlin-SNET/tresor-ecosystem)
* TRESOR Proxy
 * Overview
 * How to install and run
 * Functionalities in the Proxy
 * Code structure and design rationale
 * Extending the proxy
* TCTP
 * Overview
 * Demo: Enable secure End-to-end encryption
* TRESOR Broker: SDL
 * Overview
 * Syntax of Service Descriptions
 * Code structure and design rationale
 * Extending the SDL
* TRESOR Broker
 * Vocabulary
 * API overview
 * Code structure and design rationale
 * Demo: Describing a service
* Further functionality
 * Single Sign-On Authentication
 * Authorization through XACML
 * Creating access policies through TRESOR PAP
 * Unified Logging

**Comment by lodygens** [comment]
I am interested. 
Is there any requirements? Should we be familiar with ruby?
Since it's all freeware, it's always interesting to install, deploy and run from sources.

**Comment by Josyab** [comment]
Hello Mathias, all,

I believe it would be interesting to include a kind of "hands-on" topic in
which CYCLONE attendees could really work with TRESOR ecosystem experience
with it.

I would propose something similar to the following:

   - Install and run (or in case it takes too much time to prepare a VM
   with all requirements to be downloaded).
   - And prepare a "hello world" use case that can be done by attendees
   during the tutorial, so that they can get really familiar with TRESOR
   ecosystem.

Of course, Demos are also important.

Does this make sense to you? Would this be feasible?
Kind Regards,
Jose



2015-02-24 11:27 GMT+01:00 Mathias Slawik <notifications@github.com>:

> I'd like to collect your opinions on what we should present you about the
> TRESOR components.
>
> Possible topics include, but are not limited to:
>
>    - TRESOR Ecosystem
>       - Overview
>       - Fig-based demo deployment
>       <https://github.com/TU-Berlin-SNET/tresor-ecosystem>
>     - TRESOR Proxy
>       - Overview
>       - How to install and run
>       - Functionalities in the Proxy
>     - TCTP
>       - Overview
>       - Demo: Enable secure End-to-end encryption
>     - TRESOR Broker: SDL
>       - Overview
>       - Syntax of Service Descriptions
>     - TRESOR Broker
>       - Vocabulary
>       - API overview
>       - Demo: Describing a service
>     - Further functionality
>       - Single Sign-On Authentication
>       - Authorization through XACML
>       - Creating access policies through TRESOR PAP
>       - Unified Logging
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/44>.
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by mathiasslawik** [comment]
Hi Jose,

Great idea. It should be very feasible, as we have the whole ecosystem in a ready-to-use fig-based Docker-deployment. We could also create a VM automatically using Vagrant containing all ecosystem components for everyone to get “hands on” experience with the TRESOR components.

We could adapt our standard “TRESOR” demo to a “hello world” use case for the participants, e.g., describing a service in the broker, accessing it through the proxy and looking at the central logging data for example.

I am currently leaning towards having a three-part tutorial. The first part would be "non-technical" overview, the second some "hands on" time using the components and the third part would be going through some of the code to know, where to integrate. What do you think?

Best regards,
Mathias

**Comment by Josyab** [comment]
Hi Mathias,

Exactly. I like this three-step approach for the TRESOR tutorial (and also
for the rest of the SW to be integrated in CYCLONE).
For OpenNaaS we are thinking on the following structure:

1.- Non-technical webinar on OpenNaaS.
2.- Hands on:

   - 1st exercise ("hello world" level)
   - 2nd exercise (Optional). Something a little bit more complex
   - 3rd exercise (optional). "The challenge": Something more ambitious for
   those who want to go further and squeeze the tutorial.

3.- How to integrate/extend OpenNaaS to be part of the solution ( As
Mathias proposes: "some of the code to know, where to integrate").

I believe this should work. Please, I would like the rest of the partners
to take a look on this structure and add any additional point we should be
including in the tutorials.

Kind Regards,
Jose

2015-02-26 13:53 GMT+01:00 Mathias Slawik <notifications@github.com>:

> Hi Jose,
>
> Great idea. It should be very feasible, as we have the whole ecosystem in
> a ready-to-use fig-based Docker-deployment. We could also create a VM
> automatically using Vagrant containing all ecosystem components for
> everyone to get “hands on” experience with the TRESOR components.
>
> We could adapt our standard “TRESOR” demo to a “hello world” use case for
> the participants, e.g., describing a service in the broker, accessing it
> through the proxy and looking at the central logging data for example.
>
> I am currently leaning towards having a three-part tutorial. The first
> part would be "non-technical" overview, the second some "hands on" time
> using the components and the third part would be going through some of the
> code to know, where to integrate. What do you think?
>
> Best regards,
> Mathias
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/44#issuecomment-76173039>
> .
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by mathiasslawik** [comment]
Hi,

the slides are available in our share under Meetings\201504XX-TRESOR-Tutorial.

We'll circulate installation instructions in the next days.

Best regards,
Mathias
