### ISSUE TITLE
Discuss on the intergration level between TRESOR and SAML/XACML components. 

### ISSUE THREAD

**Issue by Josyab** [cyclone-project/cyclone-tracking#46]
The outcome should be to define the way they will integrate in CYCLONE

**Comment by mathiasslawik** [comment]
We (TUB/UvA) had a video conference on 20 March.

The following items are the outcome of this meeting:
* UvA and TUB consider quite different use cases for their security components. While UvA presents solutions for (amongst others) virtualized infrastructure provisioning, TUB proposes a generic authentication and authorization model for RESTful SaaS consumption by cloud consumers in federated ecosystems. It is unclear, if they are complementary or if components will have to be integrated. It depends on concrete use-cases for the CYCLONE security components.
* Both UvA and TUB have created security components utilizing XACML and SAML in the past, which can be integrated through regular HTTP communication. Both Policy Decision Points ([TRESOR-pdp](https://github.com/TU-Berlin-SNET/tresor-pdp) and [SNE-XACML](https://github.com/canhnt/sne-xacml)) are written in Java and could be integrated directly, if needed.
* UvA has provided 139 pages of deliverable documentation detailing the previous usage of UvA XACML/SAML components. TUB will study those documents.
* TUB has provided [a synopsis of TRESOR authentication and authorization](https://github.com/TU-Berlin-SNET/tresor-ecosystem#authentication-and-authorization). UvA will also participate in the TRESOR tutorial, where TUB will give more details about the AA architecture.
* As a next step TUB and UvA will contribute to a glossary and a basic abstract high-level security architecture, as concrete requirements out of the use cases are currently missing
* After this, TUB and UvA will get in direct contact to the CYCLONE partners to discuss this architecture.

**Comment by Josyab** [comment]
Hi Mathias, Yuri,

Without having expertise on this topic, and according to your description I
have a couple of questions:

1.-  Sounds like UvA solutions are more IaaS oriented and TUB ones more
SaaS oriented. I mean, like two different levels of security mechanisms
which depends of the type of service (IaaS, SaaS). Is this correct?

2.- Does "UvA solutions" present authentication and authorization
mechanisms for virtualized infrastructure provisioning (as TUB solution
does for SaaS) or do tese "Uva solutions" include any other features?

BTW, the approach you propose to set the security architecture is fine to
me. Is it maybe the case (again, i am not an expert on this) that the
security solutions proposed by TUB and UvA are suitable to different Cloud
services approaches (i.e. not necessarily compatible)? Or could it be the
case of integrating both solutions to offer different levels of security?

Bests,
Jose



2015-03-23 9:37 GMT+01:00 Mathias Slawik <notifications@github.com>:

> We (TUB/UvA) had a video conference on 20 March.
>
> The following items are the outcome of this meeting:
>
>    - UvA and TUB consider quite different use cases for their security
>    components. While UvA presents solutions for (amongst others) virtualized
>    infrastructure provisioning, TUB proposes a generic authentication and
>    authorization model for RESTful SaaS consumption by cloud consumers in
>    federated ecosystems. It is unclear, if they are complementary or if
>    components will have to be integrated. It depends on concrete use-cases for
>    the CYCLONE security components.
>    - Both UvA and TUB have created security components utilizing XACML
>    and SAML in the past, which can be integrated through regular HTTP
>    communication. Both Policy Decision Points (TRESOR-pdp
>    <https://github.com/TU-Berlin-SNET/tresor-pdp> and SNE-XACML
>    <https://github.com/canhnt/sne-xacml>) are written in Java and could
>    be integrated directly, if needed.
>    - UvA has provided 139 pages of deliverable documentation detailing
>    the previous usage of UvA XACML/SAML components. TUB will study those
>    documents.
>    - TUB has provided a synopsis of TRESOR authentication and
>    authorization
>    <https://github.com/TU-Berlin-SNET/tresor-ecosystem#authentication-and-authorization>.
>    UvA will also participate in the TRESOR tutorial, where TUB will give more
>    details about the AA architecture.
>    - As a next step TUB and UvA will contribute to a glossary and a basic
>    abstract high-level security architecture, as concrete requirements out of
>    the use cases are currently missing
>    - After this, TUB and UvA will get in direct contact to the CYCLONE
>    partners to discuss this architecture.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/46#issuecomment-84885862>
> .
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by ydemchen** [comment]
Hi Jose,

Our intention would be to integrate both solutions because their 
applications can be for different stages or places of the 
multi/inter-cloud deployment.

Dynamic/Virtualised Access Control Infrastructure  (DACI) is configured 
during cloud infrastructure services deployment and deployed together 
with the cloud services.

TRESOR may be installed as site/host based security gateway.

So, we plan to study each other's solution and propose discussion at the 
next f2f meeting in Paris.

Mathias may add/correct my vision.

Yuri

**Comment by mathiasslawik** [comment]
Hi,

I do not have enough knowledge about DACI, the other UvA approaches and our use-cases to even say, what "integration" would mean for us. I also have no idea, what reasonable scenarios we have for a possible integration. I also don't know, what functions we could validate in the CYCLONE use-cases, as we have the project goal of not implementing something, which we cannot validate in them.

That's why I find it far too early to say anything about concrete intentions.

But if Yuri has more concrete ideas, then I'd be glad if you could write them down to discuss them, e.g., what you mean by "site/host based security gateway". Maybe we need some use-case diagrams to make everything a little more clear.

I also see, that both solutions have different users, requirements and goals. So I don't know yet, how we can integrate them reasonably.

Best regards,
Mathias

Am 23.03.2015 11:57 schrieb Yuri Demchenko <notifications@github.com>:
Hi Jose,

Our intention would be to integrate both solutions because their
applications can be for different stages or places of the
multi/inter-cloud deployment.

Dynamic/Virtualised Access Control Infrastructure (DACI) is configured
during cloud infrastructure services deployment and deployed together
with the cloud services.

TRESOR may be installed as site/host based security gateway.

So, we plan to study each other's solution and propose discussion at the
next f2f meeting in Paris.

Mathias may add/correct my vision.

Yuri
