### ISSUE TITLE
MS11 - Bioinformatics use cases description and requirements 

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#82]
To carry on describing the bioinformatics use cases description initiated in task #54.
Include comments from the partners about the document CYCLONE_MS11-v2.0
Refine applications description and requirements, including the actors.

**Comment by cblanchet** [comment]
Related to the task #81

**Comment by cblanchet** [comment]
Yet, we get answers only from TUB about the security aspects.

 (See #104, #106 , #109)

**Comment by cblanchet** [comment]
I put in OneDrive a new version (3.0) of the document. Comments and remarks are welcome.

Cyclone > WP3 > Deliverables > M311

**Comment by lodygens** [comment]
dear all,
some remarks/questions:
- "may" should be preferred to "can" and "cans" ;)
- section 2.1.2.2 : why do you separate "biomedical staff" (BS) from "cloud user" (CU). I would think they are the same since you write that BS must have a cloud account. Then I guess any BS member is a CU.
- section 2.1.2.2 : you write "As a cloud provider, I can guarantee that the VM will be deployed in an user-devoted network, isolated from other users." We should ask netword specialist if this is faisable; for example, would VPN answer your need?
- section 2.1.2.4: what "R-B1" stands for? Seems a very strange notation. Should not it be Req1, Req2 etc ?
- R-B1-2 : it is not clear who provides advanced dashboard
- R-B1-6 : it is not clear who creates VM. About secured data transfert: if TCTP may be used, you should propose/list other solutions or write something explaining that other solutions may be expected
- R-B1-7 : to my mind VM should be accessible according to authorization too (not only data, I mean)
- R-B1-8 : since data are public, they may not have to be deployed by cloud provider (I mean if they are public they are certainly deployed otherwise they are not public ;) ). But certainly cloud provider should ensure they are accessible from cloud infrastructure
-R-B2-2 : is this realy a requirements? Your application really requires to be deployed over different cloud infrastructure? I think your requirement here is that you need a huge amount of computing ressources. Then you must tell how much ressources you need.
- R-B2-3 : again, by "availabel", I guess you meed accessible
- R-B2-4 : I am not sure that SSH connections can use federated identity: you should change this requirement title from "SSH connection to VM based on identity federation" to "Connection to VM based on identity federation"

- section 2.1.4 : finally, my felling is that you have GRID requirements: you need that VM should be placed near data
- section 2.1.4.2 : bioinforatician (is it english?) and engineer are cloud users

- section 3 : why do we have to describe software componenets (e.g. Stratuslab)? It is already written in Cyclone  DoA

- section 4: why do we have to describe testbed in this document? There is already M7.1. SO I only copy/paste from it...

**Comment by Josyab** [comment]
Hi Oleg, all,

Just a couple of carifications on some of your comments. I hope they help.:)

They are inline,

Best Regards,
Jose


2015-06-29 11:08 GMT+02:00 Oleg Lodygensky <notifications@github.com>:

> dear all,
> some remarks/questions:
>
>    - "may" should be preferred to "can" and "cans" ;)
>    - section 2.1.2.2 : why do you separate "biomedical staff" (BS) from
>    "cloud user" (CU). I would think they are the same since you write that BS
>    must have a cloud account. Then I guess any BS member is a CU.
>    - section 2.1.2.2 : you write "As a cloud provider, I can guarantee
>    that the VM will be deployed in an user-devoted network, isolated from
>    other users." We should ask netword specialist if this is faisable; for
>    example, would VPN answer your need?
>    - section 2.1.2.4: what "R-B1" stands for? Seems a very strange
>    notation. Should not it be Req1, Req2 etc ?
>    - R-B1-2 : it is not clear who provides advanced dashboard
>    - R-B1-6 : it is not clear who creates VM. About secured data
>    transfert: if TCTP may be used, you should propose/list other solutions or
>    write something explaining that other solutions may be expected
>    - R-B1-7 : to my mind VM should be accessible according to
>    authorization too (not only data, I mean)
>    - R-B1-8 : since data are public, they may not have to be deployed by
>    cloud provider (I mean if they are public they are certainly deployed
>    otherwise they are not public ;) ). But certainly cloud provider should
>    ensure they are accessible from cloud infrastructure -R-B2-2 : is this
>    realy a requirements? Your application really requires to be deployed over
>    different cloud infrastructure? I think your requirement here is that you
>    need a huge amount of computing ressources. Then you must tell how much
>    ressources you need.
>    - R-B2-3 : again, by "availabel", I guess you meed accessible
>    -
>
>    R-B2-4 : I am not sure that SSH connections can use federated
>    identity: you should change this requirement title from "SSH connection to
>    VM based on identity federation" to "Connection to VM based on identity
>    federation"
>    -
>
>    section 2.1.4 : finally, my felling is that you have GRID
>    requirements: you need that VM should be placed near data
>    -
>
>    section 2.1.4.2 : bioinforatician (is it english?) and engineer are
>    cloud users
>
> [Jose] Yes, i had the same question ;). In case it is a kind of trade
jargon, it´s OK to keep "bioinformatician". In case not, we can keep it,
but it´s important to ensure that the term is properly defined.

>
>    -
>
>    section 3 : why do we have to describe software componenets (e.g.
>    Stratuslab)? It is already written in Cyclone DoA
>
> [Jose]: Reading the title and description of the milestone content, "*Plan
for deployment and testing of selected use cases in Year 1*" make sense to
review "what" is going to be deployed. Some of the tools (as it is the case
of OpenNaaS) may have experience improvents and modifications since we
edited the DOA. You will see it does not consist on a heavy description but
a light introduction explaining what is the tool about. I believe is worth
to have it. The reviewers wouldwant to identity "what is going to be
deployed" in the same document.

>
>    -
>
>    section 4: why do we have to describe testbed in this document? There
>    is already M7.1. SO I only copy/paste from it...
>
> [Jose] More or less the same reasoning that above.



*@All: Guys, this document should have been finalized by the end of April.
We should already have this document ready and be able to identify the plan
for deployment and also to not be delayed with the rest of the documents
and activities. *
*This is not acceptable under any circumstance. There are sections which
are enterly empty. The ToC of the document was agreed by you all, the
partners were assigned and agreed and a calendar was agreed during the
Orsay meeting.Thus, I wonder where the problem is. *
*¡Please, @all: Go through the document, and each responsible partner
provide the required input. In case there are doubts, Christophe is the
milestone leader and you can ask him. *



>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclone-project/cyclone-tracking/issues/82#issuecomment-116547374>
> .
>



-- 
---
José Ignacio Aznar
Distributed Applications and Networks Area (DANA)
i2CAT Foundation, Barcelona, Spain
http://dana.i2cat.net

<http://dana.i2cat.net/>   <http://www.i2cat.net/en>
----------------------------------------------------------
The information contained in this electronic mail message is confidential.
It is intended solely for the use of the individual or entity to whom it is
addressed and others authorised to receive it. If the reader of this
message is not the intended recipient, you are hereby notified that any
use, copying, dissemination or disclosure of this  information is strictly
prohibited. If you receive this e-mail message in error please notify me
immediately at the address box jose.aznar@i2cat.net
---------------------------------------------------------

**Comment by Josyab** [comment]
Hi,

Thanks for your comments. My answer are inline

Cheers,
Christophe

Le 1 juil. 2015 à 10:03, José Ignacio Aznar Baranda <jose.aznar@i2cat.net<mailto:jose.aznar@i2cat.net>> a écrit :

Hi Oleg, all,

Just a couple of carifications on some of your comments. I hope they help.:)

They are inline,

Best Regards,
Jose


2015-06-29 11:08 GMT+02:00 Oleg Lodygensky <notifications@github.com<mailto:notifications@github.com>>:

dear all,
some remarks/questions:

  *   "may" should be preferred to "can" and "cans" ;)
  *   section 2.1.2.2 : why do you separate "biomedical staff" (BS) from "cloud user" (CU). I would think they are the same since you write that BS must have a cloud account. Then I guess any BS member is a CU.

In my mind, a biomedical staff becomes a cloud user once he/she gets a cloud account.


  *   section 2.1.2.2 : you write "As a cloud provider, I can guarantee that the VM will be deployed in an user-devoted network, isolated from other users." We should ask netword specialist if this is faisable; for example, would VPN answer your need?
  *   section 2.1.2.4<http://2.1.2.4/>: what "R-B1" stands for? Seems a very strange notation. Should not it be Req1, Req2 etc ?
  *   R-B1-2 : it is not clear who provides advanced dashboard

CNRS IFB through our cloud web dashboard

  *   R-B1-6 : it is not clear who creates VM. About secured data transfert: if TCTP may be used, you should propose/list other solutions or write something explaining that other solutions may be expected
  *   R-B1-7 : to my mind VM should be accessible according to authorization too (not only data, I mean)

Yes


  *   R-B1-8 : since data are public, they may not have to be deployed by cloud provider (I mean if they are public they are certainly deployed otherwise they are not public ;) ). But certainly cloud provider should ensure they are accessible from cloud infrastructure -R-B2-2 : is this realy a requirements? Your application really requires to be deployed over different cloud infrastructure? I think your requirement here is that you need a huge amount of computing ressources. Then you must tell how much ressources you need.

Public means available for everyone not deployed everywhere. In that case the cloud providers are also the bioinformaticians (IFB).


  *   R-B2-3 : again, by "availabel", I guess you meed accessible
  *   R-B2-4 : I am not sure that SSH connections can use federated identity: you should change this requirement title from "SSH connection to VM based on identity federation" to "Connection to VM based on identity federation"


There have been a European project, Moonshot (https://community.jisc.ac.uk/groups/moonshot). And a production service: Jisc (https://www.jisc.ac.uk/assent)

  *   section 2.1.4 : finally, my felling is that you have GRID requirements: you need that VM should be placed near data

  *   section 2.1.4.2 : bioinforatician (is it english?) and engineer are cloud users

[Jose] Yes, i had the same question ;). In case it is a kind of trade jargon, it´s OK to keep "bioinformatician". In case not, we can keep it, but it´s important to ensure that the term is properly defined.

Seems to be largely used ;-)
 (according to our community and google)


  *   section 3 : why do we have to describe software componenets (e.g. Stratuslab)? It is already written in Cyclone DoA

[Jose]: Reading the title and description of the milestone content, "Plan for deployment and testing of selected use cases in Year 1" make sense to review "what" is going to be deployed. Some of the tools (as it is the case of OpenNaaS) may have experience improvents and modifications since we edited the DOA. You will see it does not consist on a heavy description but a light introduction explaining what is the tool about. I believe is worth to have it. The reviewers wouldwant to identity "what is going to be deployed" in the same document.

  *   section 4: why do we have to describe testbed in this document? There is already M7.1. SO I only copy/paste from it...

[Jose] More or less the same reasoning that above.



@All: Guys, this document should have been finalized by the end of April. We should already have this document ready and be able to identify the plan for deployment and also to not be delayed with the rest of the documents and activities.
This is not acceptable under any circumstance. There are sections which are enterly empty. The ToC of the document was agreed by you all, the partners were assigned and agreed and a calendar was agreed during the Orsay meeting.Thus, I wonder where the problem is.
¡Please, @all: Go through the document, and each responsible partner provide the required input. In case there are doubts, Christophe is the milestone leader and you can ask him.

**Comment by lodygens** [comment]
hi,
concerning SSH connection useing federated identity, I have look at Moonshot (#117) where they introduce account mapping.
You should carefully read it and consider pros and cons. Your requirements should clearly define what exactly you expect. It is not the same to be able to connect to a virtual machine using an account mapping than being able to use a federated account from a virtual marchine to connect to an external service requiring a federated identity.

Please clarify your requirement.

**Comment by cblanchet** [comment]
CNRS provides the contribution

**Comment by Josyab** [comment]
Dear all,

The IRT testbed description has been integrated in the CYCLONE_MS11-v3.1 file and uploaded on Onedrive with the name CYCLONE_MS11-v3.1_IRT.

Regards,

Domenico.
