### ISSUE TITLE
MS11 - I2CAT to provide an overall description of OpenNaaS

### ISSUE THREAD

**Issue by cblanchet** [cyclone-project/cyclone-tracking#85]
Related to the task #81 
Provide a overall description of the software and focus on relevant point to satisfy use cases requirements
Level of maturity of the different components and availability in the testbed infrastructure

**Comment by lodygens** [comment]
dear all,
I don't kniw if this is the right place to ask... any way

Concerning OpenNaas, I would like to know what requirements are needed to test. I have access to Grid5000 (https://www.grid5000.fr/) and I can use it to test opennaas for Cyclone. Can glance at mediawiki/index.php/Grid5000:Network and see if this could help. 
If you think this may be interesting...

**Comment by Josyab** [comment]
OpenNaaS description was provided. In order to avoid a huge document on OpenaaS software framework, a number of sections were covered. I would propose to check waht the other software tools are bringing to the document and try to homogeise a little bit the structure for all of them (i.e. edit more or less the same sections for all the software frameworks)

**Comment by cblanchet** [comment]
i2CAT provides the contribution
